"use client"

import { useEffect, useState } from "react"
import { use } from "react"
import { api } from "@/lib/api"
import { Navbar } from "@/components/layout/navbar"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

interface SessionDetail {
  id: string
  instructorName: string
  scenario: string
  status: string
  score: number | null
  instructorNotes: string | null
  createdAt: string
  completedAt: string | null
}

interface StartResponse {
  id: string
  status: string
  apiUrl: string
}

interface TelemetryPoint {
  id: string
  timestamp: string
  speed: number
  steeringAngle: number
  positionX: number
  positionY: number
  positionZ: number
  collision: boolean
}

export default function TraineeSessionDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params)
  const [session, setSession] = useState<SessionDetail | null>(null)
  const [telemetry, setTelemetry] = useState<TelemetryPoint[]>([])
  const [starting, setStarting] = useState(false)
  const [launchInfo, setLaunchInfo] = useState<StartResponse | null>(null)
  const [startError, setStartError] = useState<string | null>(null)

  useEffect(() => {
    api.get<SessionDetail>(`/api/trainee/sessions/${id}`).then(setSession)
    api.get<TelemetryPoint[]>(`/api/telemetry/session/${id}`).then(setTelemetry)
  }, [id])

  async function startSession() {
    setStarting(true)
    setStartError(null)
    setLaunchInfo(null)
    try {
      const result = await api.post<StartResponse>(`/api/trainee/sessions/${id}/start`, {})
      setLaunchInfo(result)
      const updated = await api.get<SessionDetail>(`/api/trainee/sessions/${id}`)
      setSession(updated)
    } catch (err) {
      setStartError(err instanceof Error ? err.message : "Failed to start session")
    } finally {
      setStarting(false)
    }
  }

  function getLaunchCommand(): string {
    const token = typeof window !== "undefined" ? localStorage.getItem("accessToken") ?? "" : ""
    const apiUrl = launchInfo?.apiUrl ?? ""
    return `godot --session-id ${id} --api-url ${apiUrl} --token ${token}`
  }

  function copyCommand() {
    navigator.clipboard.writeText(getLaunchCommand())
  }

  function downloadScript() {
    if (!launchInfo) return
    const token = typeof window !== "undefined" ? localStorage.getItem("accessToken") ?? "" : ""
    const scriptContent = `# Godot Simulation Launch Script
# Generated by Simulation Platform

param(
    [string]$GodotPath = "godot"
)

$sessionId = "${id}"
$apiUrl = "${launchInfo.apiUrl}"
$token = "${token}"

Write-Host "Launching Godot simulation..."
Write-Host "  Session ID: $sessionId"
Write-Host "  API URL:    $apiUrl"

& $GodotPath "--session-id" $sessionId "--api-url" $apiUrl "--token" $token

if ($LASTEXITCODE -ne 0) {
    Write-Host "Godot exited with code: $LASTEXITCODE" -ForegroundColor Red
} else {
    Write-Host "Godot exited successfully." -ForegroundColor Green
}

Write-Host "Press any key to exit..."
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
`
    const blob = new Blob([scriptContent], { type: "application/octet-stream" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = "launch-godot.ps1"
    a.click()
    // Delay revoke to avoid race with browser download start
    setTimeout(() => URL.revokeObjectURL(url), 1000)
  }

  async function finishSession() {
    await api.post(`/api/trainee/sessions/${id}/finish`, {})
    const updated = await api.get<SessionDetail>(`/api/trainee/sessions/${id}`)
    setSession(updated)
  }

  if (!session) return null

  return (
    <div>
      <Navbar title={`Session Detail`} />
      <div className="p-6 space-y-6">
        <div className="flex items-center gap-4">
          <Badge
            variant={
              session.status === "Completed"
                ? "success"
                : session.status === "Active"
                  ? "warning"
                  : "secondary"
            }
          >
            {session.status}
          </Badge>
          <span className="text-sm text-zinc-500">
            Instructor: {session.instructorName}
          </span>
          <span className="text-sm text-zinc-500">Scenario: {session.scenario}</span>
          {session.score != null && (
            <span className="text-sm font-medium">Score: {session.score}%</span>
          )}
        </div>

        <div className="flex gap-3">
          {session.status === "Pending" && (
            <Button onClick={startSession} disabled={starting}>
              {starting ? "Starting..." : "Start Simulation"}
            </Button>
          )}
          {session.status === "Active" && (
            <Button onClick={finishSession} variant="destructive">
              Finish Simulation
            </Button>
          )}
        </div>

        {startError && (
          <Card className="border-red-300 bg-red-50">
            <CardContent className="pt-6">
              <p className="text-sm text-red-700">{startError}</p>
            </CardContent>
          </Card>
        )}

        {launchInfo && (
          <Card>
            <CardHeader>
              <CardTitle>Launch Godot Simulator</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-sm text-zinc-500">
                Launch the Godot simulator from your terminal using the command below.
              </p>
              <p className="text-xs text-amber-600 font-medium">
                Warning: This command contains your session token. Do not share it.
              </p>
              <div className="bg-zinc-100 p-3 rounded text-sm font-mono break-all select-all">
                {getLaunchCommand()}
              </div>
              <div className="flex gap-2">
                <Button size="sm" onClick={copyCommand}>
                  Copy Command
                </Button>
                <Button size="sm" variant="outline" onClick={downloadScript}>
                  Download Launch Script
                </Button>
              </div>
            </CardContent>
          </Card>
        )}

        {session.instructorNotes && (
          <Card>
            <CardHeader>
              <CardTitle>Instructor Notes</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-zinc-600">{session.instructorNotes}</p>
            </CardContent>
          </Card>
        )}

        <Card>
          <CardHeader>
            <CardTitle>Telemetry ({telemetry.length} points)</CardTitle>
          </CardHeader>
          <CardContent className="max-h-64 overflow-y-auto">
            {telemetry.length === 0 ? (
              <p className="text-sm text-zinc-500">No telemetry data available.</p>
            ) : (
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b text-left text-zinc-500">
                    <th className="pb-2 pr-2">Time</th>
                    <th className="pb-2 pr-2">Speed</th>
                    <th className="pb-2 pr-2">Steering</th>
                    <th className="pb-2">Collision</th>
                  </tr>
                </thead>
                <tbody>
                  {telemetry.slice(-50).map((t) => (
                    <tr key={t.id} className="border-b last:border-0">
                      <td className="py-1 pr-2">{new Date(t.timestamp).toLocaleTimeString()}</td>
                      <td className="py-1 pr-2">{t.speed.toFixed(1)}</td>
                      <td className="py-1 pr-2">{t.steeringAngle.toFixed(2)}</td>
                      <td className="py-1">{t.collision ? "⚠️" : "—"}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
