FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["src/backend/SimApi/SimApi.csproj", "SimApi/"]
RUN dotnet restore "SimApi/SimApi.csproj"
COPY src/backend/SimApi/ SimApi/
WORKDIR "/src/SimApi"
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
EXPOSE 8080
COPY --from=build /app .
ENTRYPOINT ["dotnet", "SimApi.dll"]
